"""
accessibility_audit.py
======================
Static WCAG 2.1 AA accessibility audit for migrated HTML documents.

Performs structural checks that complement browser-based tools (e.g. Axe DevTools).
Does NOT check colour contrast, focus order, or dynamic ARIA state — use Axe for those.

Usage
-----
    # Audit all migrated HTML files under content/
    python accessibility_audit.py

    # Audit a specific file
    python accessibility_audit.py ../content/PIT3/rest/rest_connectivity_handshake_guide.html

    # Audit all files and write report to file
    python accessibility_audit.py --output audit_report.txt

WCAG Criteria Checked
---------------------
    1.1.1  Non-text Content        — decorative images should have alt="" role="presentation"
    1.3.1  Info & Relationships    — table <th> must have scope, heading hierarchy must not skip levels
    2.4.2  Page Titled             — <title> element must be present and non-empty
    2.4.4  Link Purpose            — links must not use raw URLs or generic text as their label
    2.4.6  Headings & Labels       — headings must follow logical hierarchy (no skipped levels)
    3.1.1  Language of Page        — <html> must have a lang attribute
    4.1.2  Name, Role, Value       — links must not use javascript:void(0) as href
"""

import os
import sys
import re
import argparse
from bs4 import BeautifulSoup
from datetime import datetime

# ---------------------------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------------------------

# Descriptive link text patterns that are considered non-descriptive (WCAG 2.4.4)
NON_DESCRIPTIVE_LINK_TEXT = {
    "click here", "here", "read more", "more", "link", "this link",
    "learn more", "continue"
}

# ---------------------------------------------------------------------------
# ARGUMENT PARSING
# ---------------------------------------------------------------------------

parser = argparse.ArgumentParser(
    description="Static WCAG 2.1 AA accessibility audit for migrated HTML documents."
)
parser.add_argument(
    "paths",
    nargs="*",
    help="HTML file(s) to audit. If omitted, scans all migrated HTML under content/."
)
parser.add_argument(
    "--output", "-o",
    help="Write report to this file in addition to stdout.",
    default=None
)
parser.add_argument(
    "--fail-on-critical",
    help="Exit with code 1 if any critical issues are found.",
    action="store_true",
    dest="fail_on_critical"
)
args = parser.parse_args()


# ---------------------------------------------------------------------------
# FILE DISCOVERY
# ---------------------------------------------------------------------------

def find_migrated_html_files(root):
    """
    Find all HTML files under content/ that were generated by the migration
    pipeline — identified by the presence of class="document-content".
    Skip section listing pages (rest.html, soap.html etc.) and shared pages.
    """
    results = []
    content_dir = os.path.join(root, "content")
    if not os.path.isdir(content_dir):
        return results
    for dirpath, _, filenames in os.walk(content_dir):
        for fname in filenames:
            if not fname.endswith(".html"):
                continue
            fpath = os.path.join(dirpath, fname)
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    snippet = f.read(2000)
                if "document-content" in snippet:
                    results.append(fpath)
            except Exception:
                pass
    return sorted(results)


def find_project_root(start):
    current = os.path.abspath(start)
    while True:
        if os.path.isfile(os.path.join(current, "assets", "js", "sitemap.json")):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            return None
        current = parent


# ---------------------------------------------------------------------------
# AUDIT CHECKS
# ---------------------------------------------------------------------------

class Issue:
    def __init__(self, severity, criterion, description, element=None):
        self.severity    = severity    # "critical", "serious", "moderate", "minor"
        self.criterion   = criterion   # e.g. "1.3.1"
        self.description = description
        self.element     = element     # short string representation of the offending element

    def __str__(self):
        el = f"\n    Element: {self.element}" if self.element else ""
        return f"  [{self.severity.upper()}] WCAG {self.criterion} — {self.description}{el}"


def audit_file(filepath):
    issues = []

    with open(filepath, "r", encoding="utf-8") as f:
        html = f.read()

    soup = BeautifulSoup(html, "lxml")

    # 3.1.1 — Language of Page
    html_tag = soup.find("html")
    if html_tag and not html_tag.get("lang"):
        issues.append(Issue(
            "critical", "3.1.1",
            "<html> element is missing the lang attribute.",
            '<html> (no lang="...")'
        ))

    # 2.4.2 — Page Titled
    title = soup.find("title")
    if not title or not title.get_text(strip=True):
        issues.append(Issue(
            "serious", "2.4.2",
            "<title> element is missing or empty.",
            "<title>"
        ))

    # 2.4.6 / 1.3.1 — Heading hierarchy (no skipped levels)
    headings = soup.find_all(["h1", "h2", "h3", "h4", "h5", "h6"])
    prev_level = 0
    for h in headings:
        level = int(h.name[1])
        if level > prev_level + 1 and prev_level != 0:
            issues.append(Issue(
                "serious", "1.3.1 / 2.4.6",
                f"Heading level skipped: <h{prev_level}> followed by <h{level}>.",
                f'<{h.name}>{h.get_text(strip=True)[:60]}</{h.name}>'
            ))
        prev_level = level

    # 1.3.1 — Tables: <th> must have scope attribute
    for table in soup.find_all("table"):
        for th in table.find_all("th"):
            if not th.get("scope"):
                issues.append(Issue(
                    "moderate", "1.3.1",
                    "<th> element is missing scope attribute (should be scope=\"col\" or scope=\"row\").",
                    f'<th>{th.get_text(strip=True)[:40]}</th>'
                ))

    # 1.3.1 — Tables: data tables should have <thead>
    for table in soup.find_all("table"):
        if not table.find("thead") and table.find("th"):
            issues.append(Issue(
                "moderate", "1.3.1",
                "Table has <th> elements but no <thead> — header row should be in <thead>.",
                "<table> (missing <thead>)"
            ))

    # 1.1.1 — Non-text content: images
    for img in soup.find_all("img"):
        alt = img.get("alt")
        src = img.get("src", "")
        if alt is None:
            issues.append(Issue(
                "critical", "1.1.1",
                f"<img> is missing the alt attribute.",
                f'<img src="{src[:60]}">'
            ))
        elif alt != "" and img.get("role") == "presentation":
            # role=presentation should have alt=""
            issues.append(Issue(
                "minor", "1.1.1",
                "Decorative image (role=presentation) should have alt=\"\" not descriptive alt text.",
                f'<img src="{src[:60]}" alt="{alt}">'
            ))
        elif alt == "" and img.get("role") != "presentation":
            # Empty alt without role=presentation may be decorative but should be explicit
            issues.append(Issue(
                "minor", "1.1.1",
                "Image has alt=\"\" but is missing role=\"presentation\" — add role=\"presentation\" to confirm it is decorative.",
                f'<img src="{src[:60]}">'
            ))

    # 2.1.3 — Keyboard: scrollable <pre> and <table> blocks need tabindex="0"
    for tag in soup.find_all(["pre", "table"]):
        if not tag.get("tabindex"):
            issues.append(Issue(
                "serious", "2.1.3",
                f"<{tag.name}> may be scrollable but has no tabindex=\"0\" — keyboard users cannot scroll it.",
                f'<{tag.name}> (missing tabindex="0")'
            ))

    # 4.1.2 / 2.4.4 — Links
    for a in soup.find_all("a", href=True):
        href = a.get("href", "")
        text = a.get_text(strip=True)

        # javascript:void(0) hrefs
        if "javascript:void" in href:
            issues.append(Issue(
                "serious", "4.1.2",
                "Link uses javascript:void(0) as href — use a real anchor href=\"#id\" instead.",
                f'<a href="{href}">{text[:60]}</a>'
            ))

        # Raw URL as link text
        if text.startswith("http") and text == href:
            issues.append(Issue(
                "moderate", "2.4.4",
                "Link text is a raw URL — use descriptive text instead.",
                f'<a href="{href[:60]}">{text[:60]}</a>'
            ))

        # Generic/non-descriptive link text
        if text.lower() in NON_DESCRIPTIVE_LINK_TEXT:
            issues.append(Issue(
                "moderate", "2.4.4",
                f"Non-descriptive link text: \"{text}\" — provide meaningful link text.",
                f'<a href="{href[:60]}">{text}</a>'
            ))

        # Empty link text (no text, no aria-label)
        if not text and not a.get("aria-label"):
            issues.append(Issue(
                "serious", "4.1.2",
                "Link has no text content and no aria-label — screen readers cannot describe this link.",
                f'<a href="{href[:60]}">'
            ))

    return issues


# ---------------------------------------------------------------------------
# REPORTING
# ---------------------------------------------------------------------------

SEVERITY_ORDER = {"critical": 0, "serious": 1, "moderate": 2, "minor": 3}
SEVERITY_COUNTS = {"critical": 0, "serious": 0, "moderate": 0, "minor": 0}


def run_audit(files, project_root):
    lines = []
    total_issues = 0
    total_counts = {"critical": 0, "serious": 0, "moderate": 0, "minor": 0}

    lines.append("=" * 70)
    lines.append("  WCAG 2.1 AA Static Accessibility Audit")
    lines.append(f"  {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("=" * 70)
    lines.append(f"  Files scanned: {len(files)}")
    lines.append("")

    for fpath in files:
        rel = os.path.relpath(fpath, project_root) if project_root else fpath
        issues = audit_file(fpath)
        issues.sort(key=lambda i: SEVERITY_ORDER.get(i.severity, 9))

        if not issues:
            lines.append(f"OK  {rel}")
        else:
            lines.append(f"ISSUES  {rel}  ({len(issues)} issue{'s' if len(issues) > 1 else ''})")
            for issue in issues:
                lines.append(str(issue))
                total_counts[issue.severity] = total_counts.get(issue.severity, 0) + 1
            total_issues += len(issues)
        lines.append("")

    lines.append("=" * 70)
    lines.append("  Summary")
    lines.append("=" * 70)
    lines.append(f"  Total issues : {total_issues}")
    lines.append(f"  Critical     : {total_counts.get('critical', 0)}")
    lines.append(f"  Serious      : {total_counts.get('serious', 0)}")
    lines.append(f"  Moderate     : {total_counts.get('moderate', 0)}")
    lines.append(f"  Minor        : {total_counts.get('minor', 0)}")
    lines.append("=" * 70)
    lines.append("")
    lines.append("  NOTE: This is a static analysis only. Run Axe DevTools in-browser")
    lines.append("  to check colour contrast, focus order, and dynamic ARIA state.")
    lines.append("=" * 70)

    return lines, total_counts


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

script_dir   = os.path.dirname(os.path.abspath(__file__))
project_root = find_project_root(script_dir)

if args.paths:
    files = [os.path.abspath(p) for p in args.paths]
    for f in files:
        if not os.path.isfile(f):
            print(f"Error: file not found: {f}")
            sys.exit(1)
else:
    if project_root is None:
        print("Error: could not locate project root.")
        sys.exit(1)
    files = find_migrated_html_files(project_root)
    if not files:
        print("No migrated HTML files found under content/.")
        sys.exit(0)

report_lines, counts = run_audit(files, project_root)
report_text = "\n".join(report_lines)

print(report_text)

if args.output:
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(report_text)
    print(f"\nReport written to: {args.output}")

if args.fail_on_critical and counts.get("critical", 0) > 0:
    sys.exit(1)
